#!/bin/bash
# vim: set ts=4 sts=4 sw=4 et:

stderr() {
    echo -e "$@" >&2
}

die() {
    stderr "$@"
    exit 1
}

[[ -n "$AWS_ACCESS_KEY_ID" ]] || die "AWS_ACCESS_KEY_ID is empty"
[[ -n "$AWS_SECRET_ACCESS_KEY" ]] || die "AWS_SECRET_ACCESS_KEY is empty"
[[ -n "$AWS_DEFAULT_REGION" ]] || die "AWS_DEFAULT_REGION is empty"
[[ -n "$AWS_BUCKET" ]] || die "AWS_BUCKET is empty"

# Substitute the AWS configuration into nginx.conf
sed -i -e "s:@AWS_ACCESS_KEY_ID@:${AWS_ACCESS_KEY_ID}:g" /etc/nginx/nginx.conf
sed -i -e "s:@AWS_SECRET_ACCESS_KEY@:${AWS_SECRET_ACCESS_KEY}:g" /etc/nginx/nginx.conf
sed -i -e "s:@AWS_DEFAULT_REGION@:${AWS_DEFAULT_REGION}:g" /etc/nginx/nginx.conf
sed -i -e "s:@AWS_BUCKET@:${AWS_BUCKET}:g" /etc/nginx/nginx.conf

# run nginx
exec /usr/sbin/nginx "$@"
